### ISSUE TITLE
[BUG] Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist

### ISSUE THREAD

**Issue by zhusulai** [bengarrett/RetroTxt#151] opened 2022-11-02 14:31 UTC
**Describe the bug**
Getting `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.` error when try to activate retrotxt. I'm using it to view plain text logs from Jenkins. The error only happens with V5.0.0 of the extension. Downgrading to v4.2.0 and it works.

**To Reproduce**
1. Go to plain text log page in Jenkins.
2. Click on the retrotxt button in the toolbar. 
3. No reaction.
4. Turn on developer mode and look at the extension process, I see `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.` in the console. 

**Screenshots**

**RetroTxt (access Options and click the about tab)**
- Version 5.0.0

**Browser (please complete the following information):**
 - OS: Mac
 - Browser: Opera (Beta)
 - Version: 92.0.4561.11 (x86_64)

**Additional context**

**Comment by bengarrett** [comment] 2022-11-04 08:11
Hi, thanks for the report.

Are you able to give a sample log or text file that's throwing this error?

Also, are the logs causing this error hosted online or are they being viewed locally, ie after you have downloaded them?

**Comment by bengarrett** [comment] 2022-11-04 08:22
Just to make sure the extension installed is working, does this URL work okay with your browser? It should display an ANSI of the RetroTxt logo.

https://retrotxt.com/e/preview_02.ans

**Comment by bengarrett** [comment] 2022-11-10 10:27
I've loaded a docker instance of the latest Jenkins v3.36xx. 

There is no obvious way to follow, _1. Go to plain text log page in Jenkins._
If there are no further clarifications on the reproduce instructions, such as the Jenkin's version, types of logs (build, system?) and the URL I will have to close this as I cannot reproduce.

**Closed** 2022-11-12 11:45 UTC
Labels: bug, wontfix
