### ISSUE TITLE
<tag> like text not being escaped

### ISSUE THREAD

**Issue by shalak** [bengarrett/RetroTxt#58] opened 2019-01-09 06:40 UTC
**Describe the bug**
Sometimes data is missing from rendered output if it contains "<"

**To Reproduce**
Open the attached file in RetroTXT

**Expected behavior**
All data visible

**Screenshots**
Render output:
![rendered](https://user-images.githubusercontent.com/1536554/50881347-9b903780-13e1-11e9-80ed-f4d0508a5aec.png)
Raw data:
![raw](https://user-images.githubusercontent.com/1536554/50881350-9d59fb00-13e1-11e9-85f4-bc9d3643e972.png)

**Desktop (please complete the following information):**
- OS: Ubuntu Linux 18.04 LTS
- Browser Firefox
- Version 64.0

**Additional context**
NOTE: lack of colored "INFO" is due to issue #57

**Comment by bengarrett** [comment] 2019-01-09 20:34
Hi @shalak, thanks for bringing this up. I haven't looked thoroughly into this but a quick glance shows the issue isn't specifically with the **<** character. Rather it's the combination of **<>** to form an HTML5-like tag.

This is why data such as `<missing data>` is not shown. The browser is treating it as a `<missing data></missing data>` tag and drops the unsupported element, in this case, your data.

I thought there was already code in place in RetroTxt to escape <tag like text> to avoid this, but maybe something is overriding it.

**Comment by shalak** [comment] 2019-01-10 08:31
I did check that, and without the `>` character, the data is still missing.

**Comment by bengarrett** [comment] 2019-01-13 02:41
I believe they are both the same issue where a less-than symbol and text `<example` get interpreted as a HTML tag.

Source input:
```
Some text and <less than

<open tag>
```

RetroTxt output:
![tag error](https://user-images.githubusercontent.com/513842/51080940-a4ae3b00-1738-11e9-9822-3dfb743db208.PNG)

**Comment by bengarrett** [comment] 2019-02-26 03:09
Fixed, this will be included in the next release.

**Closed by bengarrett** 2019-02-26 03:09 UTC
Labels: bug
